### ISSUE TITLE
Exception raised while running computer method on server thread SPAM

### ISSUE THREAD

**Issue by DekiruDev** [ZeroNoRyouki/ZeroCore-OLD#32]
I'm running the FTB Revelation modpack and our server has been spewing these errors. I was told to update zerocore on the host discord but I can't since it's a modpack and it will cause tons of issues but I reckon I'll report the issue and see if it can be addressed.

This is a regular occurrence and sometimes it doesn't happen for days. othertimes it happens a lot

Console snippet below

> [10:33:47] [Server thread/ERROR] [zerocore]: Exception raised while running computer method on server thread
java.lang.IllegalArgumentException: Invalid argument 0, valid range is 0 : 100
at it.zerono.mods.zerocore.lib.compat.LuaHelper.raiseIllegalArgumentRange(LuaHelper.java:137) ~[LuaHelper.class:?]
at it.zerono.mods.zerocore.lib.compat.LuaHelper.getIntFromArgs(LuaHelper.java:74) ~[LuaHelper.class:?]
at erogenousbeef.bigreactors.common.multiblock.computer.ReactorComputerPeripheral.setAllControlRodLevels(ReactorComputerPeripheral.java:375) ~[ReactorComputerPeripheral.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308) [SpongeImplHooks.class:1.12.2-2838-7.2.0]
at net.minecraft.server.MinecraftServer.redirect$zje000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by ZeroNoRyouki** [comment]
Like the error say, something on your server is calling setAllControlRodLevels() on a Reactor with an insertion level that's outside the valid range of 0-100
You have to find and fix that program

**Comment by DekiruDev** [comment]
I'll see if I can find it but AFAIK nobody is using Extreme reactors. also, nobody was online at the time. unless it was chunkloaded. I'll investigate this. Thanks for your feedback

**Comment by ZeroNoRyouki** [comment]
What I can tell you is that the method referenced in your log is only called by an opencomputer lua program
