### ISSUE TITLE
crash report :(

### ISSUE THREAD

**Issue by AlphaBuzz** [ZeroNoRyouki/ZeroCore-OLD#33]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  WolfArmorCore (wolfarmor-1.12.2-3.7.5-universal-signed.jar)
  ObfuscatePlugin (obfuscate-0.2.3-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  CreativePatchingLoader (CreativeCore_v1.10.47_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 3/9/21 12:50 PM
Description: Initializing game

java.lang.NoClassDefFoundError: it/zerono/mods/zerocore/lib/init/fixer/IGameObjectDataWalker
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:93)
	at it.zerono.mods.zerocore.lib.init.GameObjectsHandler.<init>(GameObjectsHandler.java:52)
	at erogenousbeef.bigreactors.init.ObjectsHandler.<init>(ObjectsHandler.java:51)
	at erogenousbeef.bigreactors.common.BigReactors.<init>(BigReactors.java:276)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraftforge.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:191)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:599)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: it.zerono.mods.zerocore.lib.init.fixer.IGameObjectDataWalker
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 49 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:93)
	at it.zerono.mods.zerocore.lib.init.GameObjectsHandler.<init>(GameObjectsHandler.java:52)
	at erogenousbeef.bigreactors.init.ObjectsHandler.<init>(ObjectsHandler.java:51)
	at erogenousbeef.bigreactors.common.BigReactors.<init>(BigReactors.java:276)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraftforge.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:191)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:599)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1590851312 bytes (1517 MB) / 2184708096 bytes (2083 MB) up to 5607784448 bytes (5348 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6016m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 122 mods loaded, 122 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                 | Source                                             | Signature                                |
	|:----- |:--------------------------------- |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                         | 1.12.2                  | minecraft.jar                                      | None                                     |
	| LC    | mcp                               | 9.42                    | minecraft.jar                                      | None                                     |
	| LC    | FML                               | 8.0.99.99               | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                             | 14.23.5.2854            | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | creativecoredummy                 | 1.0.0                   | minecraft.jar                                      | None                                     |
	| LC    | obfuscate                         | 0.2.3                   | minecraft.jar                                      | None                                     |
	| LC    | actuallyadditions                 | 1.12.2-r152             | ActuallyAdditions-1.12.2-r152.jar                  | None                                     |
	| LC    | aether_legacy                     | 1.5.3.1                 | aether-1.12.2-v1.5.3.1.jar                         | None                                     |
	| LC    | orbis-lib                         | 0.2.0                   | orbis-lib-1.12.2-0.2.0+build411.jar                | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LC    | aether                            | 0.3.0                   | aether_ii-1.12.2-0.3.0+build411-universal.jar      | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LC    | creativecore                      | 1.10.0                  | CreativeCore_v1.10.47_mc1.12.2.jar                 | None                                     |
	| LC    | ambientsounds                     | 3.0                     | AmbientSounds_v3.1.5_mc1.12.2.jar                  | None                                     |
	| LC    | jei                               | 4.16.1.301              | jei_1.12.2-4.16.1.301.jar                          | None                                     |
	| LC    | appleskin                         | 1.0.14                  | AppleSkin-mc1.12-1.0.14.jar                        | None                                     |
	| LC    | ctm                               | MC1.12.2-1.0.2.31       | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
	| LC    | appliedenergistics2               | rv6-stable-7            | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LC    | aquaculture                       | 1.6.8                   | Aquaculture-1.12.2-1.6.8.jar                       | None                                     |
	| LC    | baubles                           | 1.5.2                   | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LC    | biomesoplenty                     | 7.0.1.2441              | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar      | None                                     |
	| LC    | bonsaitrees                       | 1.1.4                   | bonsaitrees-1.1.4-b170.jar                         | None                                     |
	| LC    | bookshelf                         | 2.3.590                 | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | buildcraftlib                     | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LC    | buildcraftcore                    | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LC    | buildcraftbuilders                | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LC    | buildcrafttransport               | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LC    | buildcraftsilicon                 | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LC    | buildcraftenergy                  | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LC    | ic2                               | 2.8.170-ex112           | industrialcraft-2-2.8.170-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LC    | forestry                          | 5.8.2.387               | forestry_1.12.2-5.8.2.387.jar                      | None                                     |
	| LC    | buildcraftcompat                  | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LC    | buildcraftfactory                 | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LC    | buildcraftrobotics                | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LC    | chameleon                         | 1.12-4.1.3              | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LC    | chesttransporter                  | 2.8.8                   | ChestTransporter-1.12.2-2.8.8.jar                  | None                                     |
	| LC    | chisel                            | MC1.12.2-1.0.2.45       | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
	| LC    | chiselsandbits                    | 14.33                   | chiselsandbits-14.33.jar                           | None                                     |
	| LC    | codechickenlib                    | 3.2.3.358               | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux                      | 2.1.1                   | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LC    | cofhcore                          | 4.6.6                   | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LC    | cofhworld                         | 1.4.0                   | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LC    | waila                             | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LC    | darkutils                         | 1.8.230                 | DarkUtils-1.12.2-1.8.230.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | endercore                         | 1.12.2-0.5.76           | EnderCore-1.12.2-0.5.76.jar                        | None                                     |
	| LC    | thaumcraft                        | 6.1.BETA26              | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
	| LC    | thermalfoundation                 | 2.6.7                   | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LC    | thermalexpansion                  | 5.5.7                   | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
	| LC    | enderio                           | 5.2.66                  | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LC    | enderiointegrationtic             | 5.2.66                  | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LC    | enderiobase                       | 5.2.66                  | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LC    | enderioconduits                   | 5.2.66                  | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LC    | enderioconduitsappliedenergistics | 5.2.66                  | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LC    | enderioconduitsopencomputers      | 5.2.66                  | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LC    | enderioconduitsrefinedstorage     | 5.2.66                  | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LC    | enderiointegrationforestry        | 5.2.66                  | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LC    | mantle                            | 1.12-1.3.3.55           | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LC    | twilightforest                    | 3.11.1021               | twilightforest-1.12.2-3.11.1021-universal.jar      | None                                     |
	| LC    | tconstruct                        | 1.12.2-2.13.0.183       | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LC    | enderiointegrationticlate         | 5.2.66                  | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LC    | enderioinvpanel                   | 5.2.66                  | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LC    | enderiomachines                   | 5.2.66                  | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LC    | enderiopowertools                 | 5.2.66                  | EnderIO-1.12.2-5.2.66.jar                          | None                                     |
	| LC    | extrautils2                       | 1.0                     | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LC    | zerocore                          | 1.12.2-0.1.2.9          | zerocore-1.12.2-0.1.2.9.jar                        | None                                     |
	| L     | bigreactors                       | 1.12.2-0.4.5.63         | ExtremeReactors-1.12.2-0.4.5.63.jar                | None                                     |
	| L     | forgelin                          | 1.8.4                   | Forgelin-1.8.4.jar                                 | None                                     |
	| L     | forgemultipartcbe                 | 2.6.2.83                | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| L     | microblockcbe                     | 2.6.2.83                | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| L     | minecraftmultipartcbe             | 2.6.2.83                | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| L     | cfm                               | 6.3.1                   | furniture-6.3.1-1.12.2.jar                         | None                                     |
	| L     | mekanism                          | 1.12.2-9.8.3.390        | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
	| L     | teslacorelib                      | 1.0.17                  | tesla-core-lib-1.12.2-1.0.17.jar                   | None                                     |
	| L     | industrialforegoing               | 1.12.2-1.12.2           | industrialforegoing-1.12.2-1.12.13-237.jar         | None                                     |
	| L     | inventorypets                     | 2.0.12                  | inventorypets-1.12-2.0.12.jar                      | None                                     |
	| L     | ironchest                         | 1.12.2-7.0.67.844       | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| L     | journeymap                        | 1.12.2-5.7.1            | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| L     | jeresources                       | 0.9.2.60                | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
	| L     | magicbees                         | 1.0                     | MagicBees-1.12.2-3.1.10.jar                        | None                                     |
	| L     | mcwdoors                          | 1.0                     | mcw-doors-1.0.0-mc1.12.2.jar                       | None                                     |
	| L     | mcwwindows                        | 1.0                     | mcw-windows-1.0.0-mc1.12.2.jar                     | None                                     |
	| L     | mekanismgenerators                | 1.12.2-9.8.3.390        | MekanismGenerators-1.12.2-9.8.3.390.jar            | None                                     |
	| L     | mekanismtools                     | 1.12.2-9.8.3.390        | MekanismTools-1.12.2-9.8.3.390.jar                 | None                                     |
	| L     | mekores                           | 2.0.13                  | mekores-2.0.13.jar                                 | None                                     |
	| L     | moreoverlays                      | 1.15.1                  | moreoverlays-1.15.1-mc1.12.2.jar                   | None                                     |
	| L     | mousetweaks                       | 2.10                    | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
	| L     | mrtjpcore                         | 2.1.4.43                | MrTJPCore-1.12.2-2.1.4.43-universal.jar            | None                                     |
	| L     | naturescompass                    | 1.8.5                   | NaturesCompass-1.12.2-1.8.5.jar                    | None                                     |
	| L     | neat                              | 1.4-17                  | Neat 1.4-17.jar                                    | None                                     |
	| L     | projectred-core                   | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-Base.jar               | None                                     |
	| L     | projectred-exploration            | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-world.jar              | None                                     |
	| L     | matteroverdrive                   | 0.7.0.0                 | MatterOverdrive-1.12.2-0.7.1.0-universal.jar       | None                                     |
	| L     | netherendingores                  | 1.12.2-1.4.2            | Netherending-Ores-1.12.2-1.4.2.jar                 | None                                     |
	| L     | harvestcraft                      | 1.12.2zb                | Pam's HarvestCraft 1.12.2zg.jar                    | None                                     |
	| L     | pamscookables                     | 1.1                     | pamscookables-1.1.jar                              | None                                     |
	| L     | patchouli                         | 1.0-23.6                | Patchouli-1.0-23.6.jar                             | None                                     |
	| L     | projectred-compat                 | 1.0                     | ProjectRed-1.12.2-4.9.4.120-compat.jar             | None                                     |
	| L     | projectred-integration            | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-integration.jar        | None                                     |
	| L     | projectred-transmission           | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-integration.jar        | None                                     |
	| L     | projectred-fabrication            | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-fabrication.jar        | None                                     |
	| L     | projectred-illumination           | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-lighting.jar           | None                                     |
	| L     | projectred-expansion              | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-mechanical.jar         | None                                     |
	| L     | projectred-relocation             | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-mechanical.jar         | None                                     |
	| L     | projectred-transportation         | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-mechanical.jar         | None                                     |
	| L     | railcraft                         | 12.0.0                  | railcraft-12.0.0.jar                               | None                                     |
	| L     | rustic                            | 1.1.7                   | rustic-1.1.7.jar                                   | None                                     |
	| L     | thermaldynamics                   | 2.5.6                   | ThermalDynamics-1.12.2-2.5.6.1-universal.jar       | None                                     |
	| L     | simplyjetpacks                    | 1.12.2-2.2.19.0         | SimplyJetpacks2-1.12.2-2.2.19.0.jar                | None                                     |
	| L     | stg                               | 1.12.2-1.2.2            | stg-1.12.2-1.2.2.jar                               | None                                     |
	| L     | storagedrawers                    | 5.2.2                   | StorageDrawers-1.12.2-5.4.2.jar                    | None                                     |
	| L     | thermalcultivation                | 0.3.6                   | ThermalCultivation-1.12.2-0.3.6.1-universal.jar    | None                                     |
	| L     | thermalinnovation                 | 0.3.6                   | ThermalInnovation-1.12.2-0.3.6.1-universal.jar     | None                                     |
	| L     | tinkersaether                     | 1.3.0                   | tinkersaether-1.3.0.jar                            | None                                     |
	| L     | tcomplement                       | 1.12.2-0.4.3            | TinkersComplement-1.12.2-0.4.3.jar                 | None                                     |
	| L     | tinkersjei                        | 1.2                     | tinkersjei-1.2.jar                                 | None                                     |
	| L     | uppers                            | 0.0.6                   | Uppers-0.0.6.jar                                   | None                                     |
	| L     | vc                                | 5.9.16                  | ViesCraft-1.12.2-5.9.16.jar                        | None                                     |
	| L     | waystones                         | 4.1.0                   | Waystones_1.12.2-4.1.0.jar                         | None                                     |
	| L     | wolfarmor                         | 3.7.5                   | wolfarmor-1.12.2-3.7.5-universal-signed.jar        | None                                     |
	| L     | wrcbe                             | 2.3.2                   | WR-CBE-1.12.2-2.3.2.33-universal.jar               | None                                     |
	| L     | phosphor-lighting                 | 1.12.2-0.2.6            | phosphor-1.12.2-0.2.6+build50.jar                  | None                                     |
	| L     | structurize                       | 1.12.2-0.10.277-RELEASE | structurize-1.12.2-0.10.277-RELEASE.jar            | None                                     |
	| L     | minecolonies                      | 1.12.2-0.11.804-RELEASE | minecolonies-1.12.2-0.11.804-RELEASE-universal.jar | None                                     |
	| L     | teslacorelib_registries           | 1.0.17                  | tesla-core-lib-1.12.2-1.0.17.jar                   | None                                     |

	Loaded coremods (and transformers): 
WolfArmorCore (wolfarmor-1.12.2-3.7.5-universal-signed.jar)
  
ObfuscatePlugin (obfuscate-0.2.3-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
CreativePatchingLoader (CreativeCore_v1.10.47_mc1.12.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8681' Renderer: 'Intel(R) HD Graphics 530'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Ender IO: No known problems detected.
	Authlib is : /E:/CurseForge%20ModPacks/Install/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Launched Version: forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 530 GL version 4.6.0 - Build 27.20.100.8681, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
	
	IK ITS LONG IKD

**Comment by AlphaBuzz** [comment]
im sorry its long but :( help

**Comment by ZeroNoRyouki** [comment]
My psychic powers tell me that you need to update Extreme Reactors

**Comment by AlphaBuzz** [comment]
yeah I alredy did it but thx 😄

**Comment by AlphaBuzz** [comment]
and how can you even read this bunch of CODES
